apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jack-clusterrolebinding
subjects:
- kind: User
  name: jack
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: jack-clusterrole
  apiGroup: rbac.authorization.k8s.io

