apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - command: ["sh"]
    args: ["-c", "while true; do echo hi; sleep2; done"]
    image: busybox:1.28.4
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
