apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cr
rules:
- apiGroups: [""]
  resources: ["pods", "service"]
  verbs: ["get", "create", "list", "update", "delete"]
  #verbs: ["*"]

- apiGroups: ["apps"]
  resources: ["deployments", "statefulSet"]
  verbs: ["get", "create", "list", "update", "delete"]

