apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod1
  name: my-pod1
spec:
  nodeName: worker1
  containers:
  - image: nginx
    name: my-pod1
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod2
  name: my-pod2
spec:
  nodeName: worker2
  containers:
  - image: nginx
    name: my-pod2
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod3
  name: my-pod3
spec:
  nodeName: master
  containers:
  - image: nginx
    name: my-pod3
  restartPolicy: Always