services:
    reverseproxy:
        image: reverse-proxy:ver1
        environment:
          - SITE1=nginx
          - SITE2=apache
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

        command: /bin/sh -c "envsubst < nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always